apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: default
spec:
  type: ExternalName
  externalName: kafka-service.kafka.svc.cluster.loc
  al
  ports:
    - port: 9092
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-service
  namespace: kafka
spec:
  ports:
    - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
        - env:
            - name: "KAFKA_ADVERTISED_LISTENERS"
              value: "INTERNAL://kafka-service:9092"
            - name: "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP"
              value: "INTERNAL:PLAINTEXT"
            - name: "KAFKA_INTER_BROKER_LISTENER_NAME"
              value: "INTERNAL"
            - name: "KAFKA_ZOOKEEPER_CONNECT"
              value: "zookeeper-service:2181"
            - name: "KAFKA_BROKER_ID"
              value: "1"
            - name: "KAFKA_LOG4J_LOGGERS"
              value: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
            - name: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
              value: "1"
            - name: "KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR"
              value: "1"
            - name: "KAFKA_TRANSACTION_STATE_LOG_MIN_ISR"
              value: "1"
            - name: "KAFKA_AUTHORIZER_CLASS_NAME"
              value: "kafka.security.authorizer.AclAuthorizer"
            - name: "KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND"
              value: "true"

          image: confluentinc/cp-kafka:7.3.2
          imagePullPolicy: IfNotPresent
          name: kafka-broker
          ports:
           - containerPort: 9092